import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children}) {
  return (
    <html lang="en">
      <meta property="og:title" content="Gowtham's Portfolio" />
      <meta property="og:description" content="MERN Stack Developer Portfolio" />
      <meta property="og:image" content="/og-image.png" />
      <meta property="og:url" content="https://gmnd-portofolio.vercel.app/" />
      <meta name="twitter:card" content="summary_large_image" />

      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
